import type { Channel } from '@/types';

export const CHANNELS: Channel[] = [
  {
    id: '1',
    name: 'General',
    description: 'Canal general para todo el centro',
    type: 'public',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 0,
    lastMessageAt: new Date().toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: 'messages-square',
    unreadCount: 0,
    lastMessage: 'Hola a todos!',
    lastMessageTime: '10:30',
  },
  {
    id: '2',
    name: 'Anuncios Oficiales',
    description: 'Comunicados del equipo directivo',
    type: 'announcement',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 0,
    lastMessageAt: new Date(Date.now() - 3600000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: 'megaphone',
    unreadCount: 0,
    lastMessage: 'Recordad el plazo de entrega de proyectos',
    lastMessageTime: 'Ayer',
  },
  {
    id: '3',
    name: 'Eventos y Actividades',
    description: 'Excursiones, hackathones y actividades del centro',
    type: 'public',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 0,
    lastMessageAt: new Date(Date.now() - 345600000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: 'calendar-fold',
    unreadCount: 0,
    lastMessage: 'Hackathon este fin de semana — ¡apuntaos!',
    lastMessageTime: '4d',
  },
  {
    id: '4',
    name: 'Ayuda y Soporte',
    description: 'Dudas generales y asistencia',
    type: 'public',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 0,
    lastMessageAt: new Date(Date.now() - 518400000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: 'message-circle-question',
    unreadCount: 0,
    lastMessage: 'Gracias por la ayuda!',
    lastMessageTime: '6d',
  },
];
