import type { Channel } from '@/types';

export const MOCK_CHANNELS: Channel[] = [
  {
    id: '1',
    name: 'General',
    description: 'Canal general para todos',
    type: 'public',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 25,
    lastMessageAt: new Date().toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: 'messages-square',
    unreadCount: 3,
    lastMessage: 'Hola a todos!',
    lastMessageTime: '10:30',
  },
  {
    id: '2',
    name: 'Anuncios Oficiales',
    description: 'Comunicados del equipo directivo',
    type: 'announcement',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 18,
    lastMessageAt: new Date(Date.now() - 3600000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: 'megaphone',
    unreadCount: 0,
    lastMessage: 'Recordad el plazo de entrega de proyectos',
    lastMessageTime: 'Ayer',
  },
  {
    id: '3',
    name: 'Eventos y Actividades',
    description: 'Excursiones, hackathones y actividades',
    type: 'public',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 12,
    lastMessageAt: new Date(Date.now() - 7200000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: 'calendar-fold',
    unreadCount: 5,
    lastMessage: 'Reunión mañana a las 10',
    lastMessageTime: '15:45',
  },
  {
    id: '4',
    name: 'Ayuda y Soporte',
    description: 'Dudas generales y asistencia',
    type: 'public',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 30,
    lastMessageAt: new Date(Date.now() - 86400000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: 'message-circle-question',
    unreadCount: 1,
    lastMessage: 'Gracias por la ayuda!',
    lastMessageTime: '2d',
  },
];
