import type { Channel } from '../types';

export const MOCK_CHANNELS: Channel[] = [
  {
    id: '1',
    name: 'General',
    description: 'Canal general para todos',
    type: 'public',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 25,
    lastMessageAt: new Date().toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: '💬',
    unreadCount: 3,
    lastMessage: 'Hola a todos!',
    lastMessageTime: '10:30',
  },
  {
    id: '2',
    name: 'Programación',
    description: 'Dudas y recursos de código',
    type: 'public',
    createdBy: 'teacher_1',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 18,
    lastMessageAt: new Date(Date.now() - 3600000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: '💻',
    unreadCount: 0,
    lastMessage: 'Alguien tiene el enlace del repo?',
    lastMessageTime: 'Ayer',
  },
  {
    id: '3',
    name: 'Proyectos',
    description: 'Coordinación de proyectos',
    type: 'public',
    createdBy: 'teacher_2',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 12,
    lastMessageAt: new Date(Date.now() - 7200000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: '📁',
    unreadCount: 5,
    lastMessage: 'Reunión mañana a las 10',
    lastMessageTime: '15:45',
  },
  {
    id: '4',
    name: 'Eventos',
    description: 'Eventos y actividades',
    type: 'public',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 30,
    lastMessageAt: new Date(Date.now() - 86400000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: '🎉',
    unreadCount: 1,
    lastMessage: 'Hackathon este fin de semana',
    lastMessageTime: '2d',
  },
  {
    id: '5',
    name: 'Ayuda',
    description: 'Soporte y asistencia',
    type: 'public',
    createdBy: 'admin',
    createdAt: new Date('2026-02-01').toISOString(),
    memberCount: 20,
    lastMessageAt: new Date(Date.now() - 172800000).toISOString(),
    departmentRestricted: false,
    allowedDepartments: [],
    icon: '❓',
    unreadCount: 0,
    lastMessage: 'Gracias por la ayuda!',
    lastMessageTime: '3d',
  },
];